version: "3.9"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
  frontend:
    build:
      context: .
      args:
        API_BASE_URL: http://backend:3000
    ports:
      - "8080:80"
    depends_on:
      - backend
