// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/data': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/data').default>>>>
    }
    '/api/participants': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/participants.get').default>>>>
    }
    '/api/participants/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/participants/[id].get').default>>>>
    }
    '/api/trainings': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/trainings.get').default>>>>
    }
    '/api/trainings/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/trainings/[id].get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}